package net.readybid.app.interactors.rfp_hotel.default_response.implementation;

import net.readybid.app.core.entities.rfp.QuestionnaireResponse;
import net.readybid.app.core.entities.rfp.QuestionnaireResponseImpl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

class RemoveVolatileAnswers {

    private final static List<String> VOLATILE_ANSWERS = createVolatileAnswersList();

    static QuestionnaireResponse from(QuestionnaireResponse response) {
        final QuestionnaireResponseImpl cleaned = new QuestionnaireResponseImpl(response);
        cleaned.getAnswers().entrySet()
                .removeIf(e -> VOLATILE_ANSWERS.contains(e.getKey()));
        return cleaned;
    }

    private static List<String> createVolatileAnswersList() {
        return Collections.unmodifiableList(Arrays.asList(
                "CLIENT_NAME", "DYNAMIC_PRICING", "DYNAMIC_PCT_Discount", "ROOMTYPE1DEFINE", "ROOMTYPE1NUMBER",
                "ROOMTYPE2DEFINE", "ROOMTYPE2NUMBER", "ROOMTYPE3DEFINE", "ROOMTYPE3NUMBER", "SEASON1START",
                "SEASON1END", "LRA_S1_RT1_SGL", "LRA_S1_RT1_DBL", "LRA_S1_RT2_SGL", "LRA_S1_RT2_DBL", "LRA_S1_RT3_SGL",
                "LRA_S1_RT3_DBL", "NLRA_S1_RT1_SGL", "NLRA_S1_RT1_DBL", "NLRA_S1_RT2_SGL", "NLRA_S1_RT2_DBL",
                "NLRA_S1_RT3_SGL", "NLRA_S1_RT3_DBL", "GOVT_S1_RT1_SGL", "GOVT_S1_RT1_DBL", "GOVT_S1_RT2_SGL",
                "GOVT_S1_RT2_DBL", "GOVT_S1_RT3_SGL", "GOVT_S1_RT3_DBL", "SEASON2START", "SEASON2END", "LRA_S2_RT1_SGL",
                "LRA_S2_RT1_DBLvLRA_S2_RT2_SGL", "LRA_S2_RT2_DBL", "LRA_S2_RT3_SGL", "LRA_S2_RT3_DBL", "NLRA_S2_RT1_SGL",
                "NLRA_S2_RT1_DBL", "NLRA_S2_RT2_SGL", "NLRA_S2_RT2_DBL", "NLRA_S2_RT3_SGL", "NLRA_S2_RT3_DBL",
                "GOVT_S2_RT1_SGL", "GOVT_S2_RT1_DBL", "GOVT_S2_RT2_SGL", "GOVT_S2_RT2_DBL", "GOVT_S2_RT3_SGL",
                "GOVT_S2_RT3_DBL", "SEASON3START", "SEASON3END", "LRA_S3_RT1_SGL", "LRA_S3_RT1_DBL", "LRA_S3_RT2_SGL",
                "LRA_S3_RT2_DBL", "LRA_S3_RT3_SGL", "LRA_S3_RT3_DBL", "NLRA_S3_RT1_SGL", "NLRA_S3_RT1_DBL",
                "NLRA_S3_RT2_SGL", "NLRA_S3_RT2_DBL", "NLRA_S3_RT3_SGL", "NLRA_S3_RT3_DBL", "GOVT_S3_RT1_SGL",
                "GOVT_S3_RT1_DBL", "GOVT_S3_RT2_SGL", "GOVT_S3_RT2_DBL", "GOVT_S3_RT3_SGL", "GOVT_S3_RT3_DBL",
                "SEASON4START", "SEASON4END", "LRA_S4_RT1_SGL", "LRA_S4_RT1_DBL", "LRA_S4_RT2_SGL", "LRA_S4_RT2_DBL",
                "LRA_S4_RT3_SGL", "LRA_S4_RT3_DBL", "NLRA_S4_RT1_SGL", "NLRA_S4_RT1_DBL", "NLRA_S4_RT2_SGL",
                "NLRA_S4_RT2_DBL", "NLRA_S4_RT3_SGL", "NLRA_S4_RT3_DBL", "GOVT_S4_RT1_SGL", "GOVT_S4_RT1_DBL",
                "GOVT_S4_RT2_SGL", "GOVT_S4_RT2_DBL", "GOVT_S4_RT3_SGL", "GOVT_S4_RT3_DBL", "SEASON5START", "SEASON5END",
                "LRA_S5_RT1_SGL", "LRA_S5_RT1_DBL", "LRA_S5_RT2_SGL", "LRA_S5_RT2_DBL", "LRA_S5_RT3_SGL",
                "LRA_S5_RT3_DBL", "NLRA_S5_RT1_SGL", "NLRA_S5_RT1_DBL", "NLRA_S5_RT2_SGL", "NLRA_S5_RT2_DBL",
                "NLRA_S5_RT3_SGL", "NLRA_S5_RT3_DBL", "GOVT_S5_RT1_SGL", "GOVT_S5_RT1_DBL", "GOVT_S5_RT2_SGL",
                "GOVT_S5_RT2_DBL", "GOVT_S5_RT3_SGL", "GOVT_S5_RT3_DBL", "COMMISSIONABLE", "COMM_PCT_CLIENT", "LOAD_GDS",
                "WALK_HOTEL", "WALK_TAX", "WALK_TRANS", "WALK_CALL", "CANC_POL", "EARLYCK_FEE", "EARLYCK_UOM",
                "EARLYCK_INCLUDE", "LODGTX_INCLUDE", "STATETX_INCLUDE", "CITYTX_INCLUDE", "VATGSTRM_INCLUDE",
                "VATGSTFB_INCLUDE", "SERVICE_INCLUDE", "OCC_INCLUDE", "OTHERTX_FEE_INCL", "PARKATTEND", "BREAK_FEE",
                "FITNESS_FEE_ON", "FITNESS_INCLUDE_ON", "LOCAL_PHONE_INCLUDE", "TOLL_CARD_CALL_INCLUDE", "HSIA_FEE",
                "HSIA_INCLUDE", "WIRELESS_FEE", "WIRELESS_INCLUDE", "AIRTRANS_FEE", "AIRTRANS_INCLUDE", "AIRTRANS_DESCRIBE",
                "OFFTRANS_INCLUDE", "RATE_SUBS", "RATE_PERSO", "RATE_CONSU", "RATE_RETIR", "RFP_CONTRACT", "RFP_NAME",
                "RFP_TITLE", "RFP_PHONECOUNTRYCODE", "RFP_PHONECITYCODE", "RFP_PHONE", "RFP_EMAIL", "RFP_DATESUBMIT",
                "USERDEFINED1", "USERDEFINED2", "USERDEFINED3", "USERDEFINED4", "USERDEFINED5", "USERDEFINED6",
                "USERDEFINED7", "USERDEFINED8", "USERDEFINED9", "USERDEFINED10", "USERDEFINED11", "USERDEFINED12",
                "USERDEFINED13", "USERDEFINED14", "USERDEFINED15", "USERDEFINED16", "USERDEFINED17", "USERDEFINED18",
                "USERDEFINED19", "USERDEFINED20", "USERDEFINED21", "USERDEFINED22", "USERDEFINED23", "USERDEFINED24",
                "USERDEFINED25", "USERDEFINED26", "USERDEFINED27", "USERDEFINED28", "USERDEFINED29", "USERDEFINED30",
                "LOS2MIN_ES", "LOS2MAX_ES", "LOS3MIN_ES", "LOS3MAX_ES", "LOS4MIN_ES", "LOS4MAX_ES", "SEASON1START_ES",
                "SEASON1END_ES", "LRA_S1_RT1_L2_ES_SGL", "LRA_S1_RT1_L2_ES_DBL", "LRA_S1_RT2_L2_ES_SGL",
                "LRA_S1_RT2_L2_ES_DBL", "LRA_S1_RT3_L2_ES_SGL", "LRA_S1_RT3_L2_ES_DBL", "NLRA_S1_RT1_L2_ES_SGL",
                "NLRA_S1_RT1_L2_ES_DBL", "NLRA_S1_RT2_L2_ES_SGL", "NLRA_S1_RT2_L2_ES_DBL", "NLRA_S1_RT3_L2_ES_SGL",
                "NLRA_S1_RT3_L2_ES_DBL", "LRA_S1_RT1_L3_ES_SGL", "LRA_S1_RT1_L3_ES_DBL", "LRA_S1_RT2_L3_ES_SGL",
                "LRA_S1_RT2_L3_ES_DBL", "LRA_S1_RT3_L3_ES_SGL", "LRA_S1_RT3_L3_ES_DBL", "NLRA_S1_RT1_L3_ES_SGL",
                "NLRA_S1_RT1_L3_ES_DBL", "NLRA_S1_RT2_L3_ES_SGL", "NLRA_S1_RT2_L3_ES_DBL", "NLRA_S1_RT3_L3_ES_SGL",
                "NLRA_S1_RT3_L3_ES_DBL", "LRA_S1_RT1_L4_ES_SGL", "LRA_S1_RT1_L4_ES_DBL", "LRA_S1_RT2_L4_ES_SGL",
                "LRA_S1_RT2_L4_ES_DBL", "LRA_S1_RT3_L4_ES_SGL", "LRA_S1_RT3_L4_ES_DBL", "NLRA_S1_RT1_L4_ES_SGL",
                "NLRA_S1_RT1_L4_ES_DBL", "NLRA_S1_RT2_L4_ES_SGL", "NLRA_S1_RT2_L4_ES_DBL", "NLRA_S1_RT3_L4_ES_SGL",
                "NLRA_S1_RT3_L4_ES_DBL", "SEASON2START_ES", "SEASON2END_ES", "LRA_S2_RT1_L2_ES_SGL",
                "LRA_S2_RT1_L2_ES_DBL", "LRA_S2_RT2_L2_ES_SGL", "LRA_S2_RT2_L2_ES_DBL", "LRA_S2_RT3_L2_ES_SGL",
                "LRA_S2_RT3_L2_ES_DBL", "NLRA_S2_RT1_L2_ES_SGL", "NLRA_S2_RT1_L2_ES_DBL", "NLRA_S2_RT2_L2_ES_SGL",
                "NLRA_S2_RT2_L2_ES_DBL", "NLRA_S2_RT3_L2_ES_SGL", "NLRA_S2_RT3_L2_ES_DBL", "LRA_S2_RT1_L3_ES_SGL",
                "LRA_S2_RT1_L3_ES_DBL", "LRA_S2_RT2_L3_ES_SGL", "LRA_S2_RT2_L3_ES_DBL", "LRA_S2_RT3_L3_ES_SGL",
                "LRA_S2_RT3_L3_ES_DBL", "NLRA_S2_RT1_L3_ES_SGL", "NLRA_S2_RT1_L3_ES_DBL", "NLRA_S2_RT2_L3_ES_SGL",
                "NLRA_S2_RT2_L3_ES_DBL", "NLRA_S2_RT3_L3_ES_SGL", "NLRA_S2_RT3_L3_ES_DBL", "LRA_S2_RT1_L4_ES_SGL",
                "LRA_S2_RT1_L4_ES_DBL", "LRA_S2_RT2_L4_ES_SGL", "LRA_S2_RT2_L4_ES_DBL", "LRA_S2_RT3_L4_ES_SGL",
                "LRA_S2_RT3_L4_ES_DBL", "NLRA_S2_RT1_L4_ES_SGL", "NLRA_S2_RT1_L4_ES_DBL", "NLRA_S2_RT2_L4_ES_SGL",
                "NLRA_S2_RT2_L4_ES_DBL", "NLRA_S2_RT3_L4_ES_SGL", "NLRA_S2_RT3_L4_ES_DBL", "SEASON3START_ES",
                "SEASON3END_ES", "LRA_S3_RT1_L2_ES_SGL", "LRA_S3_RT1_L2_ES_DBL", "LRA_S3_RT2_L2_ES_SGL",
                "LRA_S3_RT2_L2_ES_DBL", "LRA_S3_RT3_L2_ES_SGL", "LRA_S3_RT3_L2_ES_DBL", "NLRA_S3_RT1_L2_ES_SGL",
                "NLRA_S3_RT1_L2_ES_DBL", "NLRA_S3_RT2_L2_ES_SGL", "NLRA_S3_RT2_L2_ES_DBL", "NLRA_S3_RT3_L2_ES_SGL",
                "NLRA_S3_RT3_L2_ES_DBL", "LRA_S3_RT1_L3_ES_SGL", "LRA_S3_RT1_L3_ES_DBL", "LRA_S3_RT2_L3_ES_SGL",
                "LRA_S3_RT2_L3_ES_DBL", "LRA_S3_RT3_L3_ES_SGL", "LRA_S3_RT3_L3_ES_DBL", "NLRA_S3_RT1_L3_ES_SGL",
                "NLRA_S3_RT1_L3_ES_DBL", "NLRA_S3_RT2_L3_ES_SGL", "NLRA_S3_RT2_L3_ES_DBL", "NLRA_S3_RT3_L3_ES_SGL",
                "NLRA_S3_RT3_L3_ES_DBL", "LRA_S3_RT1_L4_ES_SGL", "LRA_S3_RT1_L4_ES_DBL", "LRA_S3_RT2_L4_ES_SGL",
                "LRA_S3_RT2_L4_ES_DBL", "LRA_S3_RT3_L4_ES_SGL", "LRA_S3_RT3_L4_ES_DBL", "NLRA_S3_RT1_L4_ES_SGL",
                "NLRA_S3_RT1_L4_ES_DBL", "NLRA_S3_RT2_L4_ES_SGL", "NLRA_S3_RT2_L4_ES_DBL", "NLRA_S3_RT3_L4_ES_SGL",
                "NLRA_S3_RT3_L4_ES_DBL", "SEASON4START_ES", "SEASON4END_ES", "LRA_S4_RT1_L2_ES_SGL",
                "LRA_S4_RT1_L2_ES_DBL", "LRA_S4_RT2_L2_ES_SGL", "LRA_S4_RT2_L2_ES_DBL", "LRA_S4_RT3_L2_ES_SGL",
                "LRA_S4_RT3_L2_ES_DBL", "NLRA_S4_RT1_L2_ES_SGL", "NLRA_S4_RT1_L2_ES_DBL", "NLRA_S4_RT2_L2_ES_SGL",
                "NLRA_S4_RT2_L2_ES_DBL", "NLRA_S4_RT3_L2_ES_SGL", "NLRA_S4_RT3_L2_ES_DBL", "LRA_S4_RT1_L3_ES_SGL",
                "LRA_S4_RT1_L3_ES_DBL", "LRA_S4_RT2_L3_ES_SGL", "LRA_S4_RT2_L3_ES_DBL", "LRA_S4_RT3_L3_ES_SGL",
                "LRA_S4_RT3_L3_ES_DBL", "NLRA_S4_RT1_L3_ES_SGL", "NLRA_S4_RT1_L3_ES_DBL", "NLRA_S4_RT2_L3_ES_SGL",
                "NLRA_S4_RT2_L3_ES_DBL", "NLRA_S4_RT3_L3_ES_SGL", "NLRA_S4_RT3_L3_ES_DBL", "LRA_S4_RT1_L4_ES_SGL",
                "LRA_S4_RT1_L4_ES_DBL", "LRA_S4_RT2_L4_ES_SGL", "LRA_S4_RT2_L4_ES_DBL", "LRA_S4_RT3_L4_ES_SGL",
                "LRA_S4_RT3_L4_ES_DBL", "NLRA_S4_RT1_L4_ES_SGL", "NLRA_S4_RT1_L4_ES_DBL", "NLRA_S4_RT2_L4_ES_SGL",
                "NLRA_S4_RT2_L4_ES_DBL", "NLRA_S4_RT3_L4_ES_SGL", "NLRA_S4_RT3_L4_ES_DBL", "SEASON5START_ES",
                "SEASON5END_ES", "LRA_S5_RT1_L2_ES_SGL", "LRA_S5_RT1_L2_ES_DBL", "LRA_S5_RT2_L2_ES_SGL",
                "LRA_S5_RT2_L2_ES_DBL", "LRA_S5_RT3_L2_ES_SGL", "LRA_S5_RT3_L2_ES_DBL", "NLRA_S5_RT1_L2_ES_SGL",
                "NLRA_S5_RT1_L2_ES_DBL", "NLRA_S5_RT2_L2_ES_SGL", "NLRA_S5_RT2_L2_ES_DBL", "NLRA_S5_RT3_L2_ES_SGL",
                "NLRA_S5_RT3_L2_ES_DBL", "LRA_S5_RT1_L3_ES_SGL", "LRA_S5_RT1_L3_ES_DBL", "LRA_S5_RT2_L3_ES_SGL",
                "LRA_S5_RT2_L3_ES_DBL", "LRA_S5_RT3_L3_ES_SGL", "LRA_S5_RT3_L3_ES_DBL", "NLRA_S5_RT1_L3_ES_SGL",
                "NLRA_S5_RT1_L3_ES_DBL", "NLRA_S5_RT2_L3_ES_SGL", "NLRA_S5_RT2_L3_ES_DBL", "NLRA_S5_RT3_L3_ES_SGL",
                "NLRA_S5_RT3_L3_ES_DBL", "LRA_S5_RT1_L4_ES_SGL", "LRA_S5_RT1_L4_ES_DBL", "LRA_S5_RT2_L4_ES_SGL",
                "LRA_S5_RT2_L4_ES_DBL", "LRA_S5_RT3_L4_ES_SGL", "LRA_S5_RT3_L4_ES_DBL", "NLRA_S5_RT1_L4_ES_SGL",
                "NLRA_S5_RT1_L4_ES_DBL", "NLRA_S5_RT2_L4_ES_SGL", "NLRA_S5_RT2_L4_ES_DBL", "NLRA_S5_RT3_L4_ES_SGL",
                "NLRA_S5_RT3_L4_ES_DBL", "ADDTL_CHARGE_R1_ES", "ADDTL_CHARGE_R2_ES", "ADDTL_CHARGE_R3_ES",
                "RATE_NOTES_ES", "MTG_TAX_AMT", "MTG_TAX_UOM", "MTG_TAX_INCL", "MTG_SERVICE_AMT", "MTG_SERVICE_UOM",
                "MTG_SERVICE_INCL", "BREAKOUT_10", "BREAKOUT_25", "GROUP_S1_10-50", "GROUP_S1_51-100", "GROUP_S2_10-50",
                "GROUP_S2_51-100", "GROUP_S3_10-50", "GROUP_S3_51-100", "GROUP_S4_10-50", "GROUP_S4_51-100",
                "GROUP_S5_10-50", "GROUP_S5_51-100", "MTGPKG_FULL_10-50", "MTGPKG_HALF_10-50", "MTGPKG_FULL_51-100",
                "MTGPKG_HALF_51-100", "PARK_COMP_MTG", "LCD_COST", "LCD_INCL", "SCREEN_COST", "SCREEN_INCL",
                "HSIA_COST_MTG", "HSIA_INCL_MTG", "MTG_UserDefined1", "MTG_UserDefined2", "MTG_UserDefined3",
                "MTG_UserDefined4", "MTG_UserDefined5", "MTG_UserDefined6", "MTG_UserDefined7", "MTG_UserDefined8",
                "MTG_UserDefined9", "MTG_UserDefined10", "MTG_UserDefined11", "MTG_UserDefined12", "MTG_UserDefined13",
                "MTG_UserDefined14", "MTG_UserDefined15", "MTG_UserDefined16", "MTG_UserDefined17", "MTG_UserDefined18",
                "MTG_UserDefined19", "MTG_UserDefined20", "MTG_UserDefined21", "MTG_UserDefined22", "MTG_UserDefined23",
                "MTG_UserDefined24", "MTG_UserDefined25", "MTG_UserDefined26", "MTG_UserDefined27", "MTG_UserDefined28",
                "MTG_UserDefined29", "MTG_UserDefined30"
        ));
    }
}
