package net.readybid.app.core.entities.location.address;

public enum State {
    AL("Alabama", Country.US),
    AK("Alaska", Country.US),
    AB("Alberta", Country.CA),
    AS("American Samoa", Country.US),
    AZ("Arizona", Country.US),
    AR("Arkansas", Country.US),
    BC("British Columbia", Country.CA),
    CA("California", Country.US),
    CO("Colorado", Country.US),
    CT("Connecticut", Country.US),
    DE("Delaware", Country.US),
    DC("District of Columbia", Country.US),
    FM("Federated States of Micronesia", Country.US),
    FL("Florida", Country.US),
    GA("Georgia", Country.US),
    GU("Guam", Country.US),
    HI("Hawaii", Country.US),
    ID("Idaho", Country.US),
    IL("Illinois", Country.US),
    IN("Indiana", Country.US),
    IA("Iowa", Country.US),
    KS("Kansas", Country.US),
    KY("Kentucky", Country.US),
    LA("Louisiana", Country.US),
    ME("Maine", Country.US),
    MB("Manitoba", Country.CA),
    MH("Marshall Islands", Country.US),
    MD("Maryland", Country.US),
    MA("Massachusetts", Country.US),
    MI("Michigan", Country.US),
    MN("Minnesota", Country.US),
    MS("Mississippi", Country.US),
    MO("Missouri", Country.US),
    MT("Montana", Country.US),
    NE("Nebraska", Country.US),
    NV("Nevada", Country.US),
    NB("New Brunswick", Country.CA),
    NH("New Hampshire", Country.US),
    NJ("New Jersey", Country.US),
    NM("New Mexico", Country.US),
    NY("New York", Country.US),
    NL("Newfoundland", Country.CA),
    NC("North Carolina", Country.US),
    ND("North Dakota", Country.US),
    MP("Northern Mariana Islands", Country.US),
    NT("Northwest Territories", Country.CA),
    NS("Nova Scotia", Country.CA),
    NU("Nunavut", Country.CA),
    OH("Ohio", Country.US),
    OK("Oklahoma", Country.US),
    ON("Ontario", Country.CA),
    OR("Oregon", Country.US),
    PW("Palau", Country.US),
    PA("Pennsylvania", Country.US),
    PE("Prince Edward Island", Country.CA),
    PR("Puerto Rico", Country.US),
    QC("Quebec", Country.CA),
    RI("Rhode Island", Country.US),
    SK("Saskatchewan", Country.CA),
    SC("South Carolina", Country.US),
    SD("South Dakota", Country.US),
    TN("Tennessee", Country.US),
    TX("Texas", Country.US),
    UT("Utah", Country.US),
    VT("Vermont", Country.US),
    VI("Virgin Islands", Country.US),
    VA("Virginia", Country.US),
    WA("Washington", Country.US),
    WV("West Virginia", Country.US),
    WI("Wisconsin", Country.US),
    WY("Wyoming", Country.US),
    YT("Yukon Territory", Country.CA);

    public final Country country;
    public final String fullName;

    State(String fullName, Country country) {
        this.fullName = fullName;
        this.country = country;
    }
}
